'use strict';
const crypto=require('node:crypto'),http=require('../lib/http'),store=require('../lib/store'),actionsParser=require('../lib/fundAdjustedNav'),NAV=require('../lib/goldNav'),C=require('../lib/goldCalendar'),S=require('../lib/goldSignal'),identity=require('./goldIdentity'),{eligibility,LEDGER}=require('../lib/goldIdentity');
const hash=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
function rawHistoryValid(rows){return Array.isArray(rows)&&rows.length>0&&rows.every((r,i)=>r?.rawFields&&S.validDate(r.date)&&r.date===r.rawFields.FSRQ&&S.finite(r.nav)&&r.nav>0&&r.nav===Number(r.rawFields.DWJZ)&&['0','1'].includes(String(r.navType))&&r.navType===r.rawFields.NAVTYPE&&(r.dayChange??null)===(r.rawFields.JZZZL===''||r.rawFields.JZZZL==null?null:Number(r.rawFields.JZZZL))&&(!i||r.date<rows[i-1].date));}
function createService(deps={}){const now=deps.now||Date.now,read=deps.read||store.readJSON,write=deps.write||store.writeJSONSafe,request=deps.fetchText||http.fetchText,memory=new Map(),failures=new Map(),inflight=new Map();
  async function page(code,n){const json=JSON.parse(await request(`https://api.fund.eastmoney.com/f10/lsjz?fundCode=${code}&pageIndex=${n}&pageSize=20`,{Referer:'https://fundf10.eastmoney.com/'},20000)),raw=json.Data?.LSJZList,total=Number(json.TotalCount);if(!Array.isArray(raw)||!raw.length||!Number.isSafeInteger(total)||total<=0)throw Error('invalid_nav_page');const rows=raw.map(r=>({date:r.FSRQ,nav:Number(r.DWJZ),dayChange:r.JZZZL===''||r.JZZZL==null?null:Number(r.JZZZL),navType:r.NAVTYPE,rawFields:r}));if(!rawHistoryValid(rows)||raw.some(r=>r.FUNDCODE!=null&&String(r.FUNDCODE)!==code))throw Error('invalid_nav_row');return {rows,total};}
  async function actionsOf(code){if(deps.fetchActions)return deps.fetchActions(code);const html=await request(actionsParser.sourceUrl(code),{Referer:'https://fundf10.eastmoney.com/'},20000),labels=[...html.matchAll(/<label\b[^>]*class=["']left["'][^>]*>([\s\S]*?)<\/label>/gi)].map(m=>m[1]).filter(x=>/^\s*\d{4}年度/.test(x)),codes=[...new Set(labels.flatMap(x=>[...x.matchAll(/https?:\/\/fund\.eastmoney\.com\/(\d{6})\.html/g)].map(m=>m[1])))];if(codes.length!==1||codes[0]!==code)throw Error('actions_body_identity_mismatch');return {...actionsParser.parseActions(html,code),identityVerified:true,code};}
  function validCache(c,code){return c?.version===1&&c.code===code&&c.total===c.history?.length&&rawHistoryValid(c.history)&&Number.isFinite(c.fetchedAt)&&c.fetchedAt<=now()&&Number.isFinite(c.fullCheckedAt)&&c.fullCheckedAt<=c.fetchedAt&&c.source===`https://fundf10.eastmoney.com/jjjz_${code}.html`&&c.actions?.code===code&&c.actions.sourceUrl===actionsParser.sourceUrl(code)&&c.checksum===hash(c.history)&&c.actionsHash===hash(c.actions)&&!!NAV.adjust(c.history,c.actions,code).rows;}
  async function historyOf(code,first,old,actions){const count=Math.ceil(first.total/20),pages=Array(count);pages[0]=first;
    // Merge only across an exact verified overlap. Revisions, shrinking totals,
    // action changes and the daily checkpoint force a complete audit instead.
    if(old&&now()-old.fullCheckedAt<86400000&&first.total>=old.total&&hash(actions)===old.actionsHash){
      const oldIndex=new Map(old.history.map((r,i)=>[r.date,i]));let collected=[];
      for(let i=0;i<count;i++){if(!pages[i])pages[i]=await page(code,i+1);const p=pages[i];if(p.total!==first.total||p.rows.length!==Math.min(20,first.total-i*20))throw Error('nav_page_coverage_mismatch');collected.push(...p.rows);const overlap=collected.findIndex(r=>oldIndex.has(r.date));if(overlap<0)continue;
        const index=oldIndex.get(collected[overlap].date),tail=collected.slice(overlap),exact=tail.every((r,j)=>old.history[index+j]&&hash(r)===hash(old.history[index+j]));const merged=collected.slice(0,overlap).concat(old.history.slice(index));
        if(exact&&merged.length===first.total&&rawHistoryValid(merged))return {history:merged,fullCheckedAt:old.fullCheckedAt,refreshMode:'incremental-exact-overlap'};break;}
    }
    let next=1;await Promise.all(Array.from({length:Math.min(4,count-1)},async()=>{while(next<count){const i=next++;if(!pages[i])pages[i]=await page(code,i+1);}}));if(pages.some((p,i)=>p.total!==first.total||p.rows.length!==Math.min(20,first.total-i*20)))throw Error('nav_page_coverage_mismatch');const history=pages.flatMap(p=>p.rows);if(history.length!==first.total||!rawHistoryValid(history))throw Error('nav_history_coverage_mismatch');return {history,fullCheckedAt:now(),refreshMode:'full-audit'};
  }
  async function load(code){let old=memory.get(code);if(!old){let cached;try{cached=read(`cache/gold_nav_${code}.json`);}catch(_){}if(validCache(cached,code))old=cached;}if(old&&now()>=old.fetchedAt&&now()-old.fetchedAt<3600000&&now()-old.fullCheckedAt<86400000){memory.set(code,old);return old;}const fail=failures.get(code);if(fail&&now()>=fail.at&&now()-fail.at<300000)throw Error(fail.error);
    try{const [first,actions]=await Promise.all([page(code,1),actionsOf(code)]);if(actions.error)throw Error(actions.error);const refreshed=await historyOf(code,first,old,actions),history=refreshed.history,adjusted=NAV.adjust(history,actions,code);if(adjusted.error)throw Error(adjusted.error);const value={version:1,code,history,actions,total:first.total,checksum:hash(history),actionsHash:hash(actions),fetchedAt:now(),fullCheckedAt:refreshed.fullCheckedAt,refreshMode:refreshed.refreshMode,source:`https://fundf10.eastmoney.com/jjjz_${code}.html`};memory.set(code,value);failures.delete(code);write(`cache/gold_nav_${code}.json`,value);return value;}catch(e){failures.set(code,{at:now(),error:e.message});throw e;}}
  function fetchFull(code){if(!/^\d{6}$/.test(code||''))return Promise.reject(Error('invalid_fund_code'));if(!inflight.has(code))inflight.set(code,load(code).finally(()=>inflight.delete(code)));return inflight.get(code);}
  async function forFund(fund){const resolved=await (deps.identity||identity).resolve(fund.code),evidence=resolved.evidence,error=resolved.error||eligibility(evidence),context=C.orderContext(now(),evidence);if(error||context.error)return {error:error||context.error,evidence,context,releaseEnabled:false};let data;try{data=await fetchFull(fund.code);}catch(e){return {error:e.message,evidence,context,releaseEnabled:false};}const input=prepareInput(data,evidence,C.orderContext(now(),evidence));Object.defineProperty(input,'_liveSnapshot',{value:data,enumerable:false});return input;}
  return {fetchFull,forFund};
}
function prepareInput(data,evidence,context){const error=eligibility(evidence)||context?.error;if(error)return {error,evidence,context,releaseEnabled:false};if(data?.code!==evidence.code||data.source!==`https://fundf10.eastmoney.com/jjjz_${evidence.code}.html`||!rawHistoryValid(data.history)||data.history.some(r=>r.rawFields.FUNDCODE!=null&&String(r.rawFields.FUNDCODE)!==evidence.code)||data.total!==data.history.length||data.checksum!==hash(data.history)||data.actionsHash!==hash(data.actions))return {error:'nav_snapshot_integrity_invalid',evidence,context};if(!Number.isFinite(data.fetchedAt)||data.fetchedAt>context.knownAt||context.knownAt-data.fetchedAt>=3600000)return {error:'nav_snapshot_not_current',evidence,context};
  if(!data.actions||data.actions.code!==evidence.code||data.actions.identityVerified!==true||!Array.isArray(data.actions.dividends)||!Array.isArray(data.actions.splits))return {error:'corporate_action_identity_unverified',evidence,context};
  // Ignore unknown future economics before adjusting; every known report point
  // stays in the economic chain, then the verified daily calendar projects it.
  const view=C.compile(evidence),isKnown=d=>d<=context.asOfDate&&C.deadline(d,evidence,view)!==null&&C.deadline(d,evidence,view)<=context.knownAt,past=data.history.filter(r=>isKnown(r.date)),actions={...data.actions,dividends:data.actions.dividends.filter(a=>isKnown(a.date)),splits:data.actions.splits.filter(a=>isKnown(a.date))},adjusted=NAV.adjust(past,actions,evidence.code);
  if(adjusted.error)return {error:adjusted.error,evidence,context};const known=C.selectKnown(adjusted.rows,evidence,context);if(known.error)return {...known,evidence,context};const result=S.analyze(known.rows);
  const input={result,evidence,context,releaseEnabled:LEDGER.releaseEnabled===true,source:data.source,sourceFetchedAt:data.fetchedAt,sourceHash:data.checksum,actionHash:data.actionsHash,segmentFrom:known.segmentFrom,adjustment:adjusted.adjustment,waitingForPublication:known.waitingForPublication,missingDates:known.missingDates};Object.defineProperty(input,'_returnRows',{value:known.rows,enumerable:false});return input;}
function revalidateInput(input,t){if(!input)return input;if(input.context?.knownAt>t)return {...input,error:'historical_asof_not_supported',releaseEnabled:false};const context=C.orderContext(t,input.evidence);if(input._liveSnapshot)return prepareInput(input._liveSnapshot,input.evidence,context);return {...input,context,error:input.error||context.error,releaseEnabled:false};}
module.exports={...createService(),createService,prepareInput,revalidateInput,rawHistoryValid,hash};
