'use strict';
const assert=require('node:assert/strict'),T=require('../engines/timing'),F=require('../fixtures/goldInputs'),build=require('../engines/strategies/goldDual'),L=require('../data/goldIdentity.json');
async function run(){let today='2026-09-24',memory={'timing_state.json':{version:1,baselineDate:'2026-09-01',funds:{'000216':{lastVerdict:'add',campaignId:'old'}}},'timing_samples.json':[{type:'advice-open',code:'000216',eventDate:'2026-09-01',campaign:{id:'old',openDate:'2026-09-01'},backfill:'done'}]},old=JSON.stringify(memory['timing_samples.json']),enabled=L.releaseEnabled;
  T._forTest({today:()=>today,read:key=>memory[key],write:(key,value)=>{memory[key]=structuredClone(value);}});const dec=kind=>({...build(F.fund('000216',kind)),name:'合成黄金',category:'cycle',blockedReason:null});try{T.onDecide({'018391':{code:'018391',name:'黄金联接合成',category:'cycle',action:'add',matrix:{_type:'cycle',pctZone:'cheap',gate:'pass'}}});assert.equal(JSON.stringify(memory['timing_samples.json']),old);assert.equal(memory['timing_state.json'].funds['018391'],undefined);T.onDecide({'000216':dec('waiting')});assert.equal(memory['timing_state.json'].strategyFunds?.['gold-dual-v1'],undefined);L.releaseEnabled=true;T.onDecide({'000216':dec('waiting')});assert.equal(JSON.stringify(memory['timing_samples.json']),old);assert.equal(memory['timing_state.json'].funds['000216'].campaignId,'old');today='2026-09-25';T.onDecide({'000216':dec('candidate')});assert.equal(memory['timing_samples.json'].length,2);assert(memory['timing_samples.json'][1].campaign.id.includes('gold-dual-v1'));today='2026-10-01';T.onDecide({'000216':dec('insufficient')});assert.equal(memory['timing_samples.json'].length,2);today='2026-10-02';T.onDecide({'000216':{...dec('waiting'),blockedReason:'purchase_suspended'}});assert.equal(memory['timing_samples.json'].length,2);today='2026-10-05';T.onDecide({'000216':dec('waiting')});assert.equal(memory['timing_samples.json'].length,3);assert.equal(memory['timing_samples.json'][2].buyOnly,true);assert.equal(memory['timing_samples.json'][2].eventDate,today);assert.equal(JSON.stringify(memory['timing_samples.json'][0]),JSON.parse(old).map(JSON.stringify)[0]);assert.equal(T.stats().versionLedgers['gold-dual-v1'].open.total,1);assert.equal(T.stats().versionLedgers['gold-dual-v1'].close.total,1);
    memory['holdings.json']={funds:[{code:'000216',category:'cycle',purchases:[{date:'2026-09-01',amount:10},{date:'2026-09-26',amount:20},{date:'2026-10-06',amount:30}]}]};assert.equal(T.buyScan(),1);const purchase=memory['timing_samples.json'].at(-1);assert.equal(purchase.strategyVersion,'gold-dual-v1');assert.equal(purchase.campaign.id,memory['timing_samples.json'][1].campaign.id);const before=JSON.stringify(memory['timing_samples.json']);const result=await T.runBackfill();assert.equal(result.done,0);assert.equal(JSON.stringify(memory['timing_samples.json']),before);assert.equal(T.buyScan(),0);
    // Closing the release gate freezes all gold collection, even with a previous campaign.
    memory['timing_samples.json'].push({type:'buy',code:'000216',strategyVersion:'gold-dual-v1',eventDate:'2026-09-27',amt:40,backfill:'pending',campaign:null,pricingDate:null});
    memory['holdings.json'].funds[0].purchases.push({date:'2026-09-27',amount:40,nav:1,shares:40,pricingDate:'2026-09-27'},{date:'2026-09-28',amount:50});
    const staleAdd=dec('candidate'),staleHold=dec('waiting'),beforeDisabled=JSON.stringify(memory['timing_samples.json']);L.releaseEnabled=false;assert.equal(T.buyScan(),0);assert.equal(JSON.stringify(memory['timing_samples.json']),beforeDisabled);assert.equal((await T.runBackfill()).done,0);assert.equal(JSON.stringify(memory['timing_samples.json']),beforeDisabled);
    // An enabled decision made before closing must not change either samples or state.
    const closedState=JSON.stringify(memory['timing_state.json']);today='2026-10-06';assert.equal(staleAdd.matrix.releaseEnabled,true);assert.equal(T.onDecide({'000216':staleAdd}).opened,0);assert.equal(JSON.stringify(memory['timing_samples.json']),beforeDisabled);assert.equal(JSON.stringify(memory['timing_state.json']),closedState);
    L.releaseEnabled=true;today='2026-10-07';assert.equal(T.onDecide({'000216':staleAdd}).opened,1);const openState=JSON.stringify(memory['timing_state.json']),openSamples=JSON.stringify(memory['timing_samples.json']);L.releaseEnabled=false;today='2026-10-15';assert.equal(T.onDecide({'000216':staleHold}).closed,0);assert.equal(JSON.stringify(memory['timing_state.json']),openState);assert.equal(JSON.stringify(memory['timing_samples.json']),openSamples);
  }finally{L.releaseEnabled=enabled;T._forTest();}console.log('黄金 timing：待启用不采集、独立版本、基线/未知/拦截、购买及旧样本保护通过');}
if(require.main===module)run().catch(e=>{console.error(e);process.exitCode=1;});module.exports={run};
