'use strict';
const assert=require('node:assert/strict'),R=require('../lib/goldRecap'),Service=require('../services/goldRecap'),F=require('../fixtures/goldInputs'),D=require('./verify_gold_data'),L=require('../data/goldIdentity.json'),T=require('../engines/timing');
async function run(){let checks=0;const equal=(a,b)=>{assert.deepEqual(a,b);checks++;},rows=Array.from({length:45},(_,i)=>({date:F.shift('2026-08-01',i),close:1+i*.01})),base={type:'advice-open',code:'000216',strategyVersion:'gold-dual-v1',orderDate:'2026-08-01',backfill:'pending'};
  const good=R.evaluate(rows,base);equal(good.update.backfill,'done');equal(good.update.positive30,true);assert(Math.abs(good.update.returnPct-30)<1e-10);checks++;assert.match(good.update.returnBasis,/fees excluded/);checks++;equal(R.evaluate(rows,{...base,type:'buy'}).error,'purchase_pricing_unconfirmed');equal(R.evaluate(rows,{...base,type:'buy',purchaseConfirmed:true,pricingDate:'2026-08-01',quotedFeeRate:1}).update,good.update);equal(R.evaluate(rows,{...base,strategyVersion:'legacy'}).error,'wrong_strategy_version');equal(R.evaluate(rows,{...base,orderDate:'2026-07-31'}).error,'reference_nav_missing');equal(R.evaluate(rows.slice(0,12),base).update.backfill,'partial');equal(R.evaluate(rows.slice(0,3),base).error,'recap_unmatured');equal(R.evaluate(rows.map(r=>({...r,close:1})),base).update.positive30,false);equal(R.evaluate(rows.map((r,i)=>({...r,close:1-i*.01})),base).update.positive30,false);
  const old=L.releaseEnabled,raw=D.data(),samples=[{...structuredClone(base),sourceHash:'original-signal-nav',actionHash:'original-signal-actions'},{...base,strategyVersion:'legacy'},{...base,type:'buy',purchaseConfirmed:true,pricingDate:'2026-08-01'}],legacy=JSON.stringify(samples[1]);let calls=0;const service=Service.createService({now:()=>F.NOW,resolve:async code=>({evidence:F.evidence(code)}),fetchFull:async()=>{calls++;return raw;}});
  try{equal((await service.backfill(samples,{holdDays:30})).reason,'release_pending');equal(calls,0);L.releaseEnabled=true;const out=await service.backfill(samples,{holdDays:30});equal(out.done,2);equal(calls,1);equal(JSON.stringify(samples[1]),legacy);equal(samples[0].sourceHash,'original-signal-nav');equal(samples[0].actionHash,'original-signal-actions');equal(samples[0].recapSourceHash,raw.checksum);equal(samples[0].recapActionHash,raw.actionsHash);assert.match(samples[0].returnBasis,/dividend-reinvested/);checks++;
    const bad=Service.createService({now:()=>F.NOW,resolve:async code=>({evidence:{...F.evidence(code),samplingVerified:false}}),fetchFull:async()=>raw}),pending=structuredClone(base);equal((await bad.backfill([pending],{holdDays:30})).changed,0);equal(pending.backfill,'pending');
    const original=Service.backfill,memory={'timing_state.json':{version:1,funds:{}},'timing_samples.json':[structuredClone(base),{...base,strategyVersion:'legacy',code:'999999',backfill:'done'}]},oldRecord=JSON.stringify(memory['timing_samples.json'][1]);Service.backfill=service.backfill;T._forTest({today:()=> '2026-09-24',read:key=>memory[key],write:(key,value)=>{memory[key]=structuredClone(value);}});try{equal((await T.runBackfill()).done,1);equal(memory['timing_samples.json'][0].backfill,'done');equal(JSON.stringify(memory['timing_samples.json'][1]),oldRecord);}finally{Service.backfill=original;T._forTest();}
  }finally{L.releaseEnabled=old;}console.log('黄金 recap：'+checks+'检查；精确自身定价日/30合格观察/费用不计明示/版本隔离/真实缺证据pending通过');return checks;}
if(require.main===module)run().catch(e=>{console.error(e);process.exitCode=1;});module.exports={run};
