'use strict';
const assert=require('node:assert/strict'),F=require('../fixtures/goldInputs'),D=require('../services/goldData'),C=require('../lib/goldCalendar'),NAV=require('../lib/goldNav');
function data(){const r=F.rows(),history=r.map((x,i)=>{const rawFields={FSRQ:x.date,DWJZ:String(x.close),JZZZL:i?String((x.close/r[i-1].close-1)*100):'',NAVTYPE:'1',FUNDCODE:'000216'};return {date:x.date,nav:x.close,dayChange:i?(x.close/r[i-1].close-1)*100:null,navType:'1',rawFields};}).reverse(),actions={code:'000216',identityVerified:true,sourceUrl:'https://fundf10.eastmoney.com/fhsp_000216.html',dividends:[],splits:[]};return {version:1,code:'000216',history,actions,total:history.length,checksum:D.hash(history),actionsHash:D.hash(actions),fetchedAt:F.NOW-1000,fullCheckedAt:F.NOW-1000,source:'https://fundf10.eastmoney.com/jjjz_000216.html'};}
async function run(){let checks=0;const equal=(a,b)=>{assert.deepEqual(a,b);checks++;},e=F.evidence(),ctx=C.orderContext(F.NOW,e),raw=data(),good=D.prepareInput(raw,e,ctx);assert(good.result,good.error);checks++;equal(C.deadline('2026-09-22',e),Date.parse('2026-09-24T14:00:00+08:00'));equal(C.orderContext(Date.parse('2026-09-24T07:00:00Z'),e).futureOrder,true);equal(C.orderContext(F.NOW,{...e,rulesVerified:false}).error,'fund_calendar_unverified');equal(C.orderContext(Date.parse('2027-01-01T00:00:00Z'),e).error,'calendar_coverage_short');
  const split=structuredClone(e);split.calendars.subscription.dates=split.calendars.subscription.dates.filter(d=>d!=='2026-09-24');equal(C.orderContext(F.NOW,split).futureOrder,true);equal(C.deadline('2026-09-22',split),C.deadline('2026-09-22',e));
  const future=structuredClone(raw);future.history.unshift({date:'2026-09-24',nav:999,dayChange:1,navType:'1',rawFields:{FSRQ:'2026-09-24',DWJZ:'999',JZZZL:'1',NAVTYPE:'1',FUNDCODE:'000216'}});future.total++;future.checksum=D.hash(future.history);equal(D.prepareInput(future,e,ctx).result,good.result);
  const gap=structuredClone(raw);gap.history=gap.history.filter(r=>r.date!=='2026-09-18');const index=gap.history.findIndex(r=>r.date==='2026-09-19');gap.history[index].dayChange=(gap.history[index].nav/gap.history[index+1].nav-1)*100;gap.history[index].rawFields.JZZZL=String(gap.history[index].dayChange);gap.total=gap.history.length;gap.checksum=D.hash(gap.history);const reset=D.prepareInput(gap,e,ctx);equal(reset.missingDates,['2026-09-18']);equal(reset.segmentFrom,'2026-09-19');equal(reset.result.values.OR,null);
  equal(D.prepareInput({...raw,checksum:'bad'},e,ctx).error,'nav_snapshot_integrity_invalid');equal(D.prepareInput(raw,{...e,samplingVerified:false},ctx).error,'daily_sampling_unverified');equal(D.prepareInput({...raw,fetchedAt:F.NOW-3600000},e,ctx).error,'nav_snapshot_not_current');
  const malformed={...raw,actions:{...raw.actions,dividends:null}};malformed.actionsHash=D.hash(malformed.actions);equal(D.prepareInput(malformed,e,ctx).error,'corporate_action_identity_unverified');
  let calls=0,t=F.NOW,writes=0;const svc=D.createService({now:()=>t,read:()=>null,write:()=>{writes++;},fetchActions:async()=>raw.actions,fetchText:async url=>{calls++;const n=Number(new URL(url).searchParams.get('pageIndex'));return JSON.stringify({TotalCount:raw.total,Data:{LSJZList:raw.history.slice((n-1)*20,n*20).map(r=>r.rawFields)}});}});const [a,b]=await Promise.all([svc.fetchFull(raw.code),svc.fetchFull(raw.code)]);equal(a,b);equal(calls,16);equal(writes,1);await svc.fetchFull(raw.code);equal(calls,16);t+=3600001;const increment=await svc.fetchFull(raw.code);equal(calls,17);equal(increment.refreshMode,'incremental-exact-overlap');equal(increment.fullCheckedAt,a.fullCheckedAt);t+=86400001;const audited=await svc.fetchFull(raw.code);equal(calls,33);equal(audited.refreshMode,'full-audit');
  let attempts=0;const fail=D.createService({now:()=>t,read:()=>null,write:()=>{throw Error('failed snapshot wrote');},fetchActions:async()=>raw.actions,fetchText:async()=>{attempts++;throw Error('offline');}});await assert.rejects(fail.fetchFull(raw.code),/offline/);await assert.rejects(fail.fetchFull(raw.code),/offline/);equal(attempts,1);t+=300001;await assert.rejects(fail.fetchFull(raw.code),/offline/);equal(attempts,2);
  const economic=[{date:'2026-09-18',nav:1,navType:'1',dayChange:null},{date:'2026-09-19',nav:.9,navType:'0',dayChange:0},{date:'2026-09-21',nav:.909,navType:'1',dayChange:1}],actions={code:raw.code,identityVerified:true,dividends:[{date:'2026-09-19',amount:.1}],splits:[]},adjusted=NAV.adjust(economic,actions,raw.code);equal(adjusted.rows.length,3);equal(adjusted.rows.at(-1).close,1.01);equal(NAV.adjust(economic,{...actions,code:'999999'},raw.code).error,'corporate_action_identity_unverified');equal(NAV.adjust(economic,{...actions,dividends:[{date:'2026-09-18',amount:.1}]},raw.code).error,'seed_action_unverified');
  const partial=D.createService({now:()=>t,read:()=>null,write:()=>{throw Error('partial wrote');},fetchActions:async()=>raw.actions,fetchText:async url=>{const n=Number(new URL(url).searchParams.get('pageIndex'));return JSON.stringify({TotalCount:raw.total,Data:{LSJZList:raw.history.slice((n-1)*20,n*20-(n===2?1:0)).map(r=>r.rawFields)}});}});await assert.rejects(partial.fetchFull(raw.code),/coverage_mismatch/);checks++;
  let payload=structuredClone(raw),actionPayload=payload.actions,probeCalls=0,probeWrites=0;const probe=D.createService({now:()=>t,read:()=>null,write:()=>{probeWrites++;},fetchActions:async()=>actionPayload,fetchText:async url=>{probeCalls++;const n=Number(new URL(url).searchParams.get('pageIndex'));return JSON.stringify({TotalCount:payload.total,Data:{LSJZList:payload.history.slice((n-1)*20,n*20).map(r=>r.rawFields)}});}});await probe.fetchFull(raw.code);equal(probeCalls,16);t+=3600001;payload.history[0].nav*=1.001;payload.history[0].rawFields.DWJZ=String(payload.history[0].nav);payload.history[0].dayChange=(payload.history[0].nav/payload.history[1].nav-1)*100;payload.history[0].rawFields.JZZZL=String(payload.history[0].dayChange);equal((await probe.fetchFull(raw.code)).refreshMode,'full-audit');equal(probeCalls,32);t+=3600001;actionPayload={...payload.actions,dividends:[{date:'2010-01-01',amount:.1}]};equal((await probe.fetchFull(raw.code)).refreshMode,'full-audit');equal(probeCalls,48);equal(probeWrites,3);
  const badCache={...audited,actions:{...audited.actions,code:'999999'}};badCache.actionsHash=D.hash(badCache.actions);let cacheCalls=0;const invalidCache=D.createService({now:()=>t,read:()=>badCache,write:()=>{},fetchActions:async()=>raw.actions,fetchText:async url=>{cacheCalls++;const n=Number(new URL(url).searchParams.get('pageIndex'));return JSON.stringify({TotalCount:raw.total,Data:{LSJZList:raw.history.slice((n-1)*20,n*20).map(r=>r.rawFields)}});}});equal((await invalidCache.fetchFull(raw.code)).refreshMode,'full-audit');equal(cacheCalls,16);
  const invalidBody=D.createService({now:()=>t,read:()=>null,write:()=>{throw Error('mismatched body wrote');},fetchActions:async()=>raw.actions,fetchText:async()=>JSON.stringify({TotalCount:1,Data:{LSJZList:[{...raw.history[0].rawFields,FUNDCODE:'999999'}]}})});await assert.rejects(invalidBody.fetchFull(raw.code),/invalid_nav_row/);checks++;
  console.log('黄金 data：'+checks+'检查，完整分页/单飞/失败TTL/独立基金日期/可知缺口/完整经济链通过');return checks;}
if(require.main===module)run().catch(e=>{console.error(e);process.exitCode=1;});module.exports={data,run};
