'use strict';
const assert=require('node:assert/strict'),F=require('../fixtures/goldInputs');
async function snapshot(options={}){const config=require('../lib/config'),store=require('../lib/store'),util=require('../lib/util'),fetchers=require('../fetchers'),service=require('../services/goldData'),C=require('../lib/goldCalendar'),LEDGER=require('../data/goldIdentity.json'),undo=[],patch=(o,k,v)=>{const old=o[k];undo.push(()=>o[k]=old);o[k]=v;},kinds=['candidate','waiting','insufficient','profile_pending','suspended','future','limited'],funds=kinds.map((k,i)=>F.fund(F.codes[i],k));let t=F.NOW;
  if(options.purchaseStamp!=null)funds[0].purchaseStatus.updatedAt=options.purchaseStamp;
  const cfg=structuredClone(require('../../data/example/config.example.json'));if(options.userLimit!=null)cfg.dailyLimits[funds[0].code]=options.userLimit;
  patch(LEDGER,'releaseEnabled',options.enabled===true);patch(Date,'now',()=>t);patch(config,'getConfig',()=>cfg);patch(util,'todayStr',()=> '2026-09-24');patch(util,'shanghaiNow',()=>({ymd:'2026-09-24',hour:14,minute:30}));patch(util,'isTradingHours',()=>false);
  patch(store,'readJSON',key=>key==='holdings.json'?{funds}:key==='categories.json'?require('../../data/example/categories.example.json'):{});for(const key of ['writeJSON','writeJSONSafe','writeDecisionHistory','appendSnapshot'])patch(store,key,()=>{throw Error('unexpected test write');});patch(fetchers,'fetchNavHistory',async code=>({history:funds.find(f=>f.code===code).history,failed:false}));patch(fetchers,'fetchValuation',async()=>null);patch(fetchers,'fetchHoldings',async()=>({holdings:[],reportDate:null}));
  patch(service,'forFund',async fund=>{const i=funds.findIndex(f=>f.code===fund.code),out=F.input(fund.code,kinds[i]);if(i===kinds.length-1&&options.finalInstant)t=options.finalInstant;return out;});
  // Explicit synthetic injection: live revalidation normally requires its hidden
  // complete snapshot. Tests never pretend this stub is an official source.
  patch(service,'revalidateInput',(input,at)=>({...input,context:{...C.orderContext(at,input.evidence),...(input.context.futureOrder?{futureOrder:true,orderDate:input.context.orderDate}:{})},releaseEnabled:options.enabled===true}));
  try{const analysis=require('../engines/analysis'),advice=require('../engines/advice'),built=await analysis.buildAnalysis();patch(analysis,'buildAnalysis',async()=>built);const {REGISTRY}=require('../engines/registry');patch(REGISTRY.goldDual,'builder',()=>{throw Error('duplicate gold strategy evaluation');});const card=await advice.buildAdvice('pm');return {analysis:JSON.parse(JSON.stringify(built)),advice:JSON.parse(JSON.stringify(card))};}finally{undo.reverse().forEach(fn=>fn());}}
async function run(){const out=await snapshot();assert.equal(out.advice.funds.length,7);for(const f of out.advice.funds){const sm=out.analysis.plan.scoreMap[f.code];assert.equal(f.strategyVersion,'gold-dual-v1');assert.equal(f.marketVerdict,sm.marketVerdict);assert.equal(f.verdict,sm.verdict);assert.equal(f.executable,sm.executable);assert.equal(f.score,null);assert.equal(f.valueScore,null);assert.equal(f.momentumScore,null);assert(!JSON.stringify(f).includes('"dates"'));assert(!JSON.stringify(f).includes('"availableAt"'));assert.equal(f.executable,false);}const f=out.advice.funds;assert.equal(f[0].marketVerdict,'add');assert.equal(f[0].blockedReason,'release_pending');assert.equal(f[1].marketVerdict,'hold');assert.equal(f[2].marketVerdict,null);assert.equal(f[2].verdict,null);assert.equal(f[3].marketState,'profile_unverified');assert.equal(f[4].marketVerdict,'add');assert.equal(f[4].blockedReason,'purchase_suspended');const enabled=await snapshot({enabled:true});assert.equal(enabled.advice.funds[0].executable,true);assert.equal(enabled.advice.funds[4].executable,false);assert.equal(enabled.advice.funds[6].executable,true);
  assert.equal((await snapshot({enabled:true,purchaseStamp:F.NOW+1})).advice.funds[0].blockedReason,'purchase_status_unverified');assert.equal((await snapshot({enabled:true,userLimit:0})).advice.funds[0].blockedReason,'user_limit_zero');assert.equal((await snapshot({enabled:true,finalInstant:Date.parse('2026-09-24T08:00:00Z')})).advice.funds[0].blockedReason,'future_order_recheck');
  const identity=require('../lib/goldIdentity'),legacy=require('../engines/strategies/gold'),compat=require('../engines/kernel');assert(identity.isGoldRoute({code:'999999',name:'合成黄金'}));assert.equal(legacy({code:'999999',name:'合成黄金'}).action,null);assert.equal(compat.buildFundDecision({code:'018391'},{cheapBy:'pricePercentile'}).action,null);assert.equal(identity.isGoldRoute({code:'DEMO-gold',name:'DEMO gold'}),false);assert.equal(identity.isGoldRoute({code:'999700',name:'白银期货'}),false);assert.equal(require('../data/goldIdentity.json').releaseEnabled,false);console.log('黄金 API：同次计算、默认关闭独立市场三态、7合成状态、交易限制/旧入口通过');return out;}
async function realGates(){const I=require('../services/goldIdentity'),L=require('../data/goldIdentity.json'),B=require('../engines/strategies/goldDual'),D=require('../services/goldData'),R=require('../engines/registry');for(const e of L.funds){const resolved=await I.resolve(e.code);assert(resolved.error);for(const category of ['growth','broad','cycle','dividend']){const fund={code:e.code,category,name:'masked',_goldData:await D.forFund({code:e.code})};assert.equal(R.resolveRegistry(fund).reg.type,'goldDual');assert.equal(B(fund).action,null);assert.equal(B(fund).executable,false);}}console.log('黄金实际门禁：七份额均不可执行，不凭接入名单生成ready');}
async function trimScope(){const analysis=require('../engines/analysis'),advice=require('../engines/advice'),config=require('../lib/config'),store=require('../lib/store'),timing=require('../engines/timing'),util=require('../lib/util'),P=require('../engines/decisionPipeline');for(const session of ['am','pm']){const undo=[],patch=(o,k,v)=>{const old=o[k];undo.push(()=>o[k]=old);o[k]=v;},cfg=structuredClone(require('../../data/example/config.example.json')),fund=F.fund('000217'),seed={'trim:000217':{active:true,lastFired:'2026-08-01'}},expected=structuredClone(seed);cfg.categoryPolicy[util.engineCategoryToBucket('cycle')]='frozen';fund.name='合成黄金C';fund.currentValue=120;fund.principal=100;fund.profitPct=20;
  const plan=P.runDecisionPipeline({funds:[fund],policy:cfg.categoryPolicy,dailyLimits:cfg.dailyLimits,strategyConfig:cfg,scoreConfig:require('../services/scoreConfig').getAllocCfg(cfg),now:F.NOW});patch(Date,'now',()=>F.NOW);patch(config,'getConfig',()=>cfg);patch(analysis,'buildAnalysis',async()=>({asOf:'2026-09-24',funds:[fund],allocation:[],totals:{},plan}));patch(store,'readJSON',key=>key==='signals.json'?seed:{});patch(store,'readDecisionHistory',()=>[]);patch(store,'writeDecisionHistory',()=>true);patch(store,'writeJSONSafe',(key,value)=>{if(key==='signals.json')assert.deepEqual(value,expected);return true;});patch(timing,'onDecide',()=>({opened:0,closed:0}));try{const card=await advice.buildAdvice(session);assert(!card.alerts.some(a=>a.type==='trim'||/减仓|赎回/.test((a.title||'')+(a.action||''))));assert.deepEqual(seed,expected);}finally{undo.reverse().forEach(fn=>fn());}}console.log('黄金买入范围：AM/PM不发C类卖出、旧冷却键保留');}
if(require.main===module)run().then(realGates).then(trimScope).catch(e=>{console.error(e);process.exitCode=1;});module.exports={snapshot,syntheticPayload:snapshot,run,realGates,trimScope};
