'use strict';
const LEDGER=require('../data/goldIdentity.json'),S=require('./goldSignal');
function isGoldRoute(f){if(require('./activeEquityIdentity').isOverseasActiveEquityRoute(f))return false;return !!f&&/^\d{6}$/.test(f.code||'')&&(LEDGER.funds.some(e=>e.code===f.code)||!!f._goldData||f.assetClass==='gold'||/黄金|上海金|gold/i.test([f.name,f.indexName,f.fundType].filter(Boolean).join(' ')));}
function eligibility(e){if(!e||e.identityVerified!==true||e.identityCurrentVerified===false||!e.source||!/^\d{6}$/.test(e.code||''))return 'profile_unverified';
  if(!LEDGER.funds.some(x=>x.code===e.code)||e.domestic!==true||e.otc!==true||e.currency!=='CNY'||e.kind!=='gold-etf-link'||!['spot-gold','shanghai-gold'].includes(e.group))return 'scope_unsupported';
  if(e.samplingVerified!==true||e.sampling!=='verified-daily-nav')return 'daily_sampling_unverified';
  if(e.continuityVerified!==true||!S.validDate(e.initializationFrom))return 'initialization_unverified';return null;}
function evidenceSummary(e){if(!e)return null;return {code:e.code,group:e.group,source:e.source||null,sourceSha256:e.sourceSha256||null,identitySnapshotVerified:e.identitySnapshotVerified===true,identityCurrentVerified:e.identityVerified===true,samplingVerified:e.samplingVerified===true,continuityVerified:e.continuityVerified===true,officialActionsHistoryVerified:e.officialActionsHistoryVerified===true,rulesVerified:e.rulesVerified===true,initializationFrom:e.initializationFrom||null,contractSource:e.contractSource||null,calendarCoverage:Object.fromEntries(['work','valuation','subscription'].map(k=>[k,{source:e.calendars?.[k]?.source||null,from:e.calendars?.[k]?.from||null,to:e.calendars?.[k]?.to||null}]))};}
function evidenceBlockers(e){const out=[];if(e?.identityVerified!==true)out.push('profile_unverified');if(e?.samplingVerified!==true)out.push('daily_sampling_unverified');if(e?.continuityVerified!==true||!S.validDate(e?.initializationFrom))out.push('initialization_unverified');if(e?.officialActionsHistoryVerified===false)out.push('official_actions_history_unverified');if(e?.rulesVerified!==true)out.push('fund_calendar_unverified');return out;}
module.exports={LEDGER,isGoldRoute,eligibility,evidenceSummary,evidenceBlockers};
