'use strict';
const S=require('../../lib/activeEquitySignal'),{eligibility}=require('../../lib/activeEquityIdentity');
const LABELS={candidate:'可考虑买入',waiting:'等待机会',insufficient:'无法判定',profile_unverified:'需要处理',scope_unsupported:'范围外'};
const REASONS={profile_unverified:'官方身份或份额档案尚未核验',scope_unsupported:'不属于已核验的人民币场外主动权益范围',daily_sampling_unverified:'日频净值采样的历史有效区间尚未核验',initialization_unverified:'固定序列起点或策略连续性尚未核验',fund_calendar_unverified:'基金专属申购、估值日历和公告规则尚未核验',calendar_coverage_short:'核验日历覆盖不足',publication_time_unverified:'净值公告的可知时点尚未核验',valuation_date_unverified:'净值日期不在已核验的基金估值日历中',stale_nav_over_14d:'最新可知净值已超过14个自然日',no_known_nav:'净值仍在公告等待期，尚无可用数据',nav_snapshot_not_current:'净值快照已过期或取得时间无效',active_equity_input_missing:'必要数据尚未取得'};
function reasonLabel(reason){return REASONS[reason]||(reason?.startsWith('expected_nav_gap:')?'应已公布的净值缺失：'+reason.split(':')[1]:reason);}
function buildActiveEquityDecision(fund){const input=fund?._activeEquityData||{},error=fund?.profileState==='needs_review'?'profile_unverified':input.evidence?.code!==fund?.code?'profile_unverified':input.error||eligibility(input.evidence)||input.context?.error;
  const r=error?null:input.result,reason=error||(!r?'active_equity_input_missing':r.trigger===null?[...r.A.missing,...r.B.missing].join(';'):null),unsupported=['profile_unverified','scope_unsupported','initialization_unverified'].includes(reason),state=r?.trigger===true?'candidate':r?.trigger===false?'waiting':reason==='initialization_unverified'?'profile_unverified':unsupported?reason:'insufficient',action=r?.trigger===true?'add':r?.trigger===false?'hold':null;
  const emptyA={drawdown:null,bias:null,recovery:null,rsi:null},emptyB={...emptyA,priceTrend:null,shortTrend:null,longDirection:null};
  const metrics={navDate:r?.date||null,A:r?.A.metrics||null,B:r?.B.metrics||null},conditions={A:r?.A.checks||emptyA,B:r?.B.checks||emptyB},paths=r?.paths||[];
  const evidence=input.evidence,identity=evidence?Object.fromEntries(Object.entries(evidence).filter(([k])=>k!=='qdiiCalendar')):null;
  const evidenceChecks={identity:evidence?.identityVerified===true,sampling:evidence?.samplingVerified===true&&evidence.sampling==='all-economic-nav',continuity:evidence?.continuityVerified===true&&S.validDate(evidence.initializationFrom),calendar:require('../../lib/activeEquityCalendar').validContract(evidence)};
  return {action,marketVerdict:action,verdict:action,executable:false,positionScore:null,strategyVersion:S.VERSION,unsupported,unsupportedReason:unsupported?reason:null,reasons:[action==='add'?'主动权益'+paths.map(p=>p==='A'?'回撤修复':'趋势回踩').join('、')+'条件成立':action==='hold'?'两个通道均未全部成立':LABELS[state]+'：'+reasonLabel(reason)],matrix:{_type:'activeEquity',strategyVersion:S.VERSION,inputVersion:S.INPUT_VERSION,marketState:state,marketStateLabel:LABELS[state],dataError:reason,dataErrorLabel:reasonLabel(reason),route:paths.length===2?'both':paths[0]||null,paths,pathStates:{A:r?.A.trigger===true?'buy':r?.A.trigger===false?'hold':'unknown',B:r?.B.trigger===true?'buy':r?.B.trigger===false?'hold':'unknown'},pathReasons:{A:r?.A.missing||[reason],B:r?.B.missing||[reason]},conditions,metrics,orderDate:input.context?.orderDate||null,futureOrder:input.context?.futureOrder===true,computedAt:input.context?.computedAt||null,source:input.source||null,sourceFetchedAt:input.sourceFetchedAt??null,sourceHash:input.sourceHash||null,actionHash:input.actionHash||null,initializationFrom:input.initializationFrom||input.evidence?.initializationFrom||null,adjustment:input.adjustment||null,identity,evidenceChecks,calendarVersion:input.context?.calendarVersion||null,contractSource:input.context?.contractSource||null,waitingForPublication:input.waitingForPublication||[],missingDates:input.missingDates||[],dataCaveat:input.dataCaveat||'身份、日频采样和当前规则各自核验；未通过时不使用旧行业算法',rawDecisionPrecision:true,buyOnly:true}};
}
module.exports=buildActiveEquityDecision;
