'use strict';
const S=require('../../lib/goldSignal'),{eligibility,LEDGER,evidenceSummary,evidenceBlockers}=require('../../lib/goldIdentity');
const LABELS={candidate:'可加仓',waiting:'等待机会',insufficient:'无法判定',profile_unverified:'需要处理',scope_unsupported:'暂不支持'};
const REASONS={profile_unverified:'官方身份尚未核验',scope_unsupported:'不属于首批国内黄金ETF联接范围',daily_sampling_unverified:'日频采样尚未核验',initialization_unverified:'策略起点与连续性尚未核验',fund_calendar_unverified:'基金工作、估值和申购日期尚未核验',calendar_coverage_short:'核验日历覆盖不足',release_pending:'工程候选待独立终审与用户确认启用',gold_input_missing:'完整净值数据尚未取得'};
function buildGoldDualDecision(fund){const input=fund?._goldData||{},error=fund?.profileState==='needs_review'?'profile_unverified':input.evidence?.code!==fund?.code?'profile_unverified':input.error||eligibility(input.evidence)||input.context?.error;
  const r=error?null:input.result,reason=error||(!r?'gold_input_missing':r.values.OR===null?'path_data_insufficient':null),state=r?.values.OR===true?'candidate':r?.values.OR===false?'waiting':['profile_unverified','scope_unsupported'].includes(reason)?reason:'insufficient',action=r?.values.OR===true?'add':r?.values.OR===false?'hold':null;
  const releaseEnabled=input.releaseEnabled===true&&LEDGER.releaseEnabled===true,blockers=evidenceBlockers(input.evidence);
  return {action,marketVerdict:action,verdict:action,executable:false,positionScore:null,strategyVersion:S.VERSION,unsupported:['profile_unverified','scope_unsupported'].includes(reason),unsupportedReason:['profile_unverified','scope_unsupported'].includes(reason)?reason:null,reasons:[reason?(REASONS[reason]||reason):action==='add'?'黄金'+r.paths.map(p=>p==='A'?'回撤修复':'趋势回踩').join('、')+'条件成立':'两个通道均有条件未达标'],matrix:{_type:'goldDual',strategyVersion:S.VERSION,inputVersion:S.INPUT_VERSION,marketState:state,marketStateLabel:LABELS[state],dataError:reason,dataErrorLabel:REASONS[reason]||reason,evidenceBlockers:blockers,releaseEnabled,releasePending:!releaseEnabled,releaseLabel:releaseEnabled?'已启用':'待启用',route:r?.paths.length===2?'both':r?.paths[0]||null,paths:r?.paths||[],pathStates:{A:r?.values.A===true?'buy':r?.values.A===false?'hold':'unknown',B:r?.values.B===true?'buy':r?.values.B===false?'hold':'unknown'},pathReasons:r?.missingConditions||{A:[reason],B:[reason]},conditions:r?.conditions||{A:{},B:{}},metrics:{navDate:r?.date||null,...r?.metrics},orderDate:input.context?.orderDate||null,futureOrder:input.context?.futureOrder===true,computedAt:input.context?.computedAt||null,source:input.source||null,sourceHash:input.sourceHash||null,actionHash:input.actionHash||null,sourceFetchedAt:input.sourceFetchedAt??null,initializationFrom:input.evidence?.initializationFrom||null,segmentFrom:input.segmentFrom||null,calendarVersion:input.context?.calendarVersion||null,missingDates:input.missingDates||[],waitingForPublication:input.waitingForPublication||[],identity:evidenceSummary(input.evidence),dataCaveat:'供应商修订快照与复权数学自洽不证明完整官方行动史；历史结果不保证盈利',buyOnly:true}};}
module.exports=buildGoldDualDecision;
